job_executor/app.py

The exception from  `job_service.get_jobs()` (in this case: `Connection aborted.`) in `app.py `was not properly caught and logged.

Log exception

---

wiremock/mappings/job-service.json

This is necessary since it's a mandatory field for job executor to interpret queued jobs

Add created_at to the mock response

---

tests/unit/adapter/test_local_storage.py
tests/unit/model/test_datastore_version.py
tests/unit/model/test_datastore_versions.py
tests/unit/model/test_metadata.py
tests/unit/worker/steps/test_dataset_pseudonymizer.py
tests/unit/worker/test_build_dataset_worker.py

Otherwise we risk that the tests fail since the folder may already exist, which will be the case if we abort the test execution and then attempt to re-run them
Note: we should perhaps also notify the would-be-tester that issuing a 'git restore' may be necessary to restore the repo to a "clean state" in case we fail to clean up after the tests.

Ensure that we delete the backup folder prior to executing the tests

---

job_executor/model/datastore_versions.py

Tiny fix to make the model accept a datastore with no released version.

bugfix_datastore: latest version no released version

---

job_executor/adapter/job_service.py
job_executor/adapter/local_storage.py
job_executor/adapter/pseudonym_service.py
job_executor/app.py
job_executor/config/log.py
job_executor/exception/__init__.py
job_executor/model/datastore.py
job_executor/model/metadata.py
job_executor/worker/build_dataset_worker.py
job_executor/worker/build_metadata_worker.py
job_executor/worker/steps/dataset_transformer.py
tests/unit/adapter/test_local_storage.py

Before a bump operation these files will be backed up:
* draft_version.json
* datastore_versions.json
* metadata_all__DRAFT.json
After the bump is completed these files are then deleted
* New backup and delete backup functions for local_storage adapter
* call backup functions in the manager
* smaller cleanups
* This has been tested with the datastore-testing integration tests and runs as expected
* Only log result of querying job-service for jobs if any jobs have been found waiting. This avoids the service logging excessively when no work has been queued
Next PR will be adding startup functionality that first queries for unfinished jobs. If such jobs are found the job-executor will rollback from backups to avoid being out-of-synch with reality.

Temp backup for bump

---

job_executor/app.py
job_executor/config/log.py
job_executor/domain/rollback.py
job_executor/model/datastore.py
tests/unit/domain/test_rollback.py
tests/unit/test_util.py
tests/unit/worker/test_build_metadata_worker.py

Rollback functionality for import jobs in both stages. 
* Updated datastore methods for add, patch_metadata and change_data
* New rollback functions: rollback_import_job, rollback_worker_job
* rollback_worker_job simply deletes all relevant files in working dir
* rollback_import_job now restores mutated files from backup and deletes added draft files, then returns the job to "built" to be retried
* Errors with rollback will now not only fail the job itself, but crash the app. Errors with rollback can not be accepted as they might leave the files out of sync

Rollback import jobs

---

job_executor/model/datastore_version.py
job_executor/model/datastore_versions.py
tests/unit/model/test_datastore.py

When updating the draft version or creating a new datastore version the release time should be set to seconds since epoch, and not days since epoch.
Added tests to check that the number written is above 1_000_000 (outside the range of epoch days)

Epoch seconds in files

---

job_executor/model/datastore.py

* Return from terminating conditional in delete_draft method. This should technically never happen unless there has been ad-hoc editing of datastore files. We have layers-upon-layers of validation that ensures that a CHANGE_DATA, REMOVE or PATCH_METADATA is only added to draft if there is a released version. This return is still absolutely necessary, as it further "destoys" the datastore if the bug is ever reached.
* There is one point in the bump code where the creation of a new metadata_all file was not validated through the MetadataAll model. This could result in invalid metadata_all files being written.

bugfix_delete_draft: return from terminal job path

---

job_executor/model/datastore.py
job_executor/model/metadata.py
job_executor/worker/steps/dataset_transformer.py
tests/resources/model/metadata/patch_unit_type/metadata.json
tests/resources/model/metadata/patch_unit_type/patched_metadata.json
tests/resources/model/metadata/patch_unit_type/updated_metadata.json
tests/resources/model/metadata/patched_metadata.json
tests/resources/model/metadata/updated_metadata.json
tests/resources/worker/steps/transformer/input/UTDANNING.json
tests/unit/model/test_metadata.py

Implementation changed as follows:
- if variable role is "Identifier" return the same object
- if variable role is "Measure" and "keyType" is used, then allow only for changing the name and represented variable's description, throw an error if any other field was attempted to be changed

Patch metadata: change implementation

---

job_executor/adapter/local_storage.py

Formats `data_versions*`, `datastore_versions.json` and `draft_version.json` with indentation.
`metadata_all*` are too big anyway so no formatting here.

Format JSON when saving datastore files

---

job_executor/adapter/local_storage.py
job_executor/app.py
job_executor/worker/build_dataset_worker.py
job_executor/worker/build_metadata_worker.py
tests/unit/worker/test_build_dataset_worker.py
tests/unit/worker/test_build_metadata_worker.py

Bugfixes for the two problems we have found recently:
* Workers do not clean up after themselves in the working directory on failure
* Workers are started before the job is tagged as "initiated" and so there is a chance of two jobs working on the same dataset
* Added unit tests
* Tested changes with integration test repo

Bug fix workers

---

job_executor/app.py
tests/unit/adapter/test_job_service.py

When system is paused it queries for built jobs and returns if any exists

Fetching built jobs when system is paused

---

job_executor/worker/steps/dataset_pseudonymizer.py
tests/unit/worker/steps/test_dataset_pseudonymizer.py

The pseudonymizer is opinionated to the order of the columns in the parquet file. This is something we might consider changing in the future, but for now the bug is fixed by adjusting the order to fit the microdata-tools output format for validated parquet

Bugfix corrupt parquet

---

job_executor/model/metadata.py
job_executor/worker/steps/dataset_transformer.py
poetry.lock
pyproject.toml
tests/resources/datastores/TEST_DATASTORE_input/BOSTED/BOSTED.json
tests/resources/datastores/TEST_DATASTORE_input/INNTEKT/INNTEKT.json
tests/resources/datastores/TEST_DATASTORE_input/KJOENN/KJOENN.json
tests/resources/datastores/TEST_DATASTORE_input/KOMMUNE_FOLKETALL/KOMMUNE_FOLKETALL.json
tests/resources/datastores/TEST_DATASTORE_input/KOMMUNE_HOYESTE_PUNKT/KOMMUNE_HOYESTE_PUNKT.json
tests/resources/datastores/TEST_DATASTORE_input/UTDANNING/UTDANNING.json
tests/resources/worker/steps/transformer/expected/KREFTREG_DS_described.json
tests/resources/worker/steps/transformer/expected/KREFTREG_DS_enumerated.json
tests/resources/worker/steps/transformer/expected/UTDANNING.json
tests/resources/worker/steps/transformer/expected/UTDANNING_PATCH.json
tests/resources/worker/steps/transformer/input_data/KREFTREG_DS_described.json
tests/resources/worker/steps/transformer/input_data/KREFTREG_DS_enumerated.json
tests/resources/worker/steps/transformer/input_data/UTDANNING.json
tests/resources/worker/steps/transformer/input_data/UTDANNING_PATCH.json

Transforms the new `temporalEnd` field into the output model taking care of the optional fields.

Expand model with TemporalEnd

---

job_executor/app.py

I pulled the code down locally and found the bugs.
This should have been caught by the editor, @haraldsvik 🤔 Check if your LSP is bugging out? 🐛 (It might also be the lack of typechecking in this top module that is messing with us)
The faulty job.dataset_name was invisible as we don't have strict typechecking on. We should clean up this top module quite a bit to make errors like these visible.

fix_manager_state_bug: invalid code in app

---

poetry.lock
pyproject.toml
tests/unit/worker/steps/test_dataset_partitioner.py

One test for partitioned datasets read the .paquet file which returns also the partitioned column. Added a test for the usual case when just asking for "start_year=123" and not "start_year=123/04f4164ec1f247f2ad392fa9c03e71fe-0.parquet".

Update pyarrow and microdata-tools

---

job_executor/adapter/local_storage.py

Added a small check that a dataset does not already exist in input_dir/archive before moving it there.
This is to avoid error when trying to reimport a dataset that is already in the archived-folder (i.e. from a previously failed import). 
Since datastore admin allows reimport of archived files/failed imports, now job-executor will only try to import the archived dataset even if a dataset with the same name also exists in the input directory. And there will be no conflicts.
If I have understood the dataflow and problem correctly - is this a sufficient solution?

MICNO-684: Added check that input file not already exist in input_dir/archive

---

job_executor/adapter/local_storage.py
job_executor/model/datastore.py
job_executor/model/metadata_all.py

- update_one: avoid persisting to files two times for dataset update operations
- write_to_json_with_tmp: avoid long writes and instead write to a tmp file and swap

Better metadata all draft write

---

.github/workflows/update-tools-version.yaml

Potential fix for [https://github.com/statisticsnorway/microdata-job-executor/security/code-scanning/11](https://github.com/statisticsnorway/microdata-job-executor/security/code-scanning/11)
[#180](https://github.com/statisticsnorway/microdata-job-executor/issues/180)
As discussed, it is not possible to add permissions to certain steps, hence the autofix-solution should be OK.

Potential fix for code scanning alert no. 11: Workflow does not contain permissions

---

job_executor/domain/datastore.py
job_executor/manager/__init__.py
tests/unit/domain/test_datastore.py
tests/unit/domain/test_empty_datastore.py
tests/unit/manager/test_manager.py

First step where functions are used rather than calling the object directly. Next step is moving logic out of the object and adding some fields in preparation of multi-tenancy. Then removing the global state entirely.

Functional interface datastore
