statisticsnorway/microdata-job-executor

- .test.env
- job_executor/adapter/job_service.py
- job_executor/adapter/local_storage.py
- job_executor/app.py
- job_executor/config/environment.py
- job_executor/config/secrets.py
- job_executor/model/datastore_version.py
- job_executor/model/datastore_versions.py
- job_executor/model/job.py
- job_executor/worker/build_dataset_worker.py
- job_executor/worker/build_metadata_worker.py
- poetry.lock
- pytest.ini
- tests/resources/input_directory/INNTEKT/INNTEKT.json
- tests/resources/secrets/secrets.json
- tests/unit/adapter/test_job_service_adapter.py
- tests/unit/worker/test_build_dataset_worker.py
- tests/unit/worker/test_build_metadata_worker.py
**IMPORTANT!** Before approving and merging this, [this branch](https://github.com/statisticsnorway/microdata-job-executor/pull/8) should be reviewed and merged into this branch. I could have included the pseudonymization functionality into this branch directly, but that would make this PR huge and less readable.
Updates to the job model, and updates done based on results from the [datastore integration tests](https://github.com/statisticsnorway/microdata-testing/pull/2).
* Update models
* Fix bugs revealed from integration testing
* Update tests
* Added secrets module from reading secrets from a file on server
> Model and test updates

- job_executor/adapter/local_storage.py
- job_executor/worker/build_dataset_worker.py
- job_executor/worker/build_metadata_worker.py
- tests/unit/worker/test_build_dataset_worker.py
- tests/unit/worker/test_build_metadata_worker.py
Not sure if we should delete additional files, please advise!
> Delete left-over csv files after these have been processed

- job_executor/adapter/local_storage.py
- job_executor/model/datastore.py
- poetry.lock
- pyproject.toml
- tests/resources/expected/KJOENN.json
- tests/unit/model/test_datastore.py
- tests/unit/worker/test_build_dataset_worker.py
* Delete <dataset_name>__DRAFT.json in working directory after metadata is imported by manager
* Add asserts to check if this file is properly deleted
* Updated dependencies + microdata-validator version and edited one piece of test data that broke because of this
* Delete archived input dir files, and added asserts to check for this
> Delete metadata draft on import

- job_executor/adapter/local_storage.py
- job_executor/app.py
- job_executor/model/datastore.py
- tests/unit/adapter/test_local_storage.py
- tests/unit/model/test_datastore.py
- added checking for tmp directory when application starts up
> Delete tmp directory when bump manifesto invalid

- job_executor/model/job.py
- tests/unit/adapter/test_job_service.py
Updated the model for Job and fixed one typo (logs => log)
> Job model update

- job_executor/app.py
- job_executor/domain/rollback.py
- job_executor/model/data_structure_update.py
- job_executor/model/datastore.py
- job_executor/model/datastore_version.py
- job_executor/model/job.py
- tests/unit/adapter/test_job_service.py
- tests/unit/model/test_datastore.py
- wiremock/mappings/job-service.json
Tested with datastatore-testing together with other changes in job-service and datastore-admin.
> rename_change_data: rename

- job_executor/adapter/local_storage.py
> version_bug_fix: fixed version bug

- poetry.lock
- pyproject.toml
- tests/resources/expected/KJOENN.json
> Validator changes

- poetry.lock
- pyproject.toml
Use new validator that cleans up working directory when unexpected exceptions occur.
Also move dependencies to the new Poetry dev section.
> Use validator 7.3.3

- job_executor/adapter/pseudonym_service.py
- job_executor/worker/steps/dataset_pseudonymizer.py
- poetry.lock
- pyproject.toml
Using the type definitions from microdata-tools for UnitIdType
> UnitType & UnitIdType for Type Safety

- job_executor/domain/rollback.py
- tests/unit/domain/test_rollback.py
Removed old files from test resources.
Removed old files and added new files from rollback file-list
> Updated rollback file list

- job_executor/adapter/job_service.py
- job_executor/app.py
- job_executor/model/maintenance_status.py
- tests/unit/adapter/test_job_service.py
- wiremock/mappings/job-service.json
Add a request to job-service/maintanence-status
- Returns early with a dict of empty lists
- Does not query for jobs
- Query for jobs 
- Returns dict with list of potential jobs
> Check Maintenance status

- job_executor/worker/steps/dataset_pseudonymizer.py
- tests/unit/worker/steps/test_dataset_partitioner.py
- tests/unit/worker/steps/test_dataset_pseudonymizer.py
- Cast values to string before sending it to pseudonymizer.
- Set specific type when writing to parquet again
- Added tests to verify parquet column types are as expected
> Pseudonymizer stricter schema

- Dockerfile
- job_executor/adapter/local_storage.py
- job_executor/model/datastore_version.py
Necessary update in order to use python 3.12.
> MICNO-28: Updated Dockerfile builder

- .github/workflows/update-tools-version.yaml
Added a new workflow which runs every hour. 
It compares local version of microdata-tools against latest pypi version.
Not sure how to test the workflow without merging it to master 🤔
> GA to check, update and create PR on Tools change - MICNO-226

- .github/workflows/update-tools-version.yaml
note: commented out reviewers as it was not found..
> cleanup for readability

- .github/workflows/update-tools-version.yaml
Change cron schedule from hourly to daily
> Updated Cron schedule to daily

- job_executor/config/log.py
will fix the filter problem in a separate pr
> error_stack_fix

- job_executor/app.py
- job_executor/domain/rollback.py
- warn about rollback
- warn about fixing interrupted jobs
- warn about dead workers
> Change logging levels

- .github/workflows/test-and-build.yaml
> Deploy prod option

- job_executor/adapter/job_service.py
- job_executor/adapter/local_storage.py
- job_executor/app.py
- job_executor/domain/rollback.py
- job_executor/manager/__init__.py
- job_executor/model/datastore.py
- job_executor/model/metadata.py
- job_executor/model/worker.py
- job_executor/worker/build_dataset_worker.py
- job_executor/worker/build_metadata_worker.py
- job_executor/worker/steps/dataset_pseudonymizer.py
- job_executor/worker/steps/dataset_transformer.py
Low hanging fruit before I add the metadata write functionality:
- Use the type definitions we already have more strictly
- Update Union typing I came across
- Found one bug in local_storage which always return None instead of bool. It is always falsey
> strict_type_cleanup: low hanging fruit & 1 bug

- job_executor/adapter/job_service.py
- tests/unit/adapter/test_job_service.py
- wiremock/mappings/job-service.json
Use the new maintenance-statuses api in datastore-api
`GET /maintenance-status -> GET /maintenance-statuses/latest`
See https://github.com/statisticsnorway/microdata-datastore-api/pull/4
> use new maintenance-statuses api
